version: v1beta1
plugins:
  - name: go
    out: go/pkg/
    opt:
      - paths=source_relative
  - name: go-grpc
    out: go/pkg
    opt:
      - paths=source_relative
#      - require_unimplemented_servers=false
  - name: grpc-gateway
    out: go/pkg
    opt:
      - paths=source_relative
  - name: openapiv2
    out: go/pkg/
